# Generated by Django 3.1.4 on 2021-02-03 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz1',
            name='score1',
            field=models.CharField(default=1, max_length=500),
        ),
    ]
