# Generated by Django 3.1.4 on 2021-02-03 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210203_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='score1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score1', models.IntegerField(default=1)),
                ('username', models.CharField(default=1, max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='quiz1',
            name='score1',
        ),
    ]
